framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - assets/theme/
        excluded_patterns:
            - '*/.*'
            - '*/node_modules/*'
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
