twig:
    file_name_pattern: '*.twig'
    globals:
        hospital_name: '%env(HOSPITAL_NAME)%'
        hospital_url: '%env(HOSPITAL_URL)%'
        hospital_logo: '%env(HOSPITAL_LOGO)%'
        hospital_phone_number: '%env(HOSPITAL_PHONE_NUMBER)%'

when@test:
    twig:
        strict_variables: true
