core:
    resource:
        path: ../src/Core/Controller/
        namespace: App\Core\Controller
    type: attribute

app:
    resource:
        path: ../src/Presentation/Webservice/
        namespace: App\Presentation\Webservice
    type: attribute

frontend:
    resource:
        path: ../src/Presentation/Frontend/
        namespace: App\Presentation\Frontend
    type: attribute